services:
    ultimate-tic-tac-toe:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        environment: 
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        networks:
            - default